source ./env.sh
pushd ${BUILDROOT} 
if [ -d ./build_quda ];
then
  rm -rf ./build_quda
fi

mkdir  ./build_quda
cd ./build_quda

export QUDA_GPU_ARCH=sm_70

cmake ${SRCROOT}/quda \
  -G "Ninja" \
  -DQUDA_TARGET_TYPE="CUDA" \
  -DQUDA_DIRAC_CLOVER=ON \
  -DQUDA_DIRAC_DOMAIN_WALL=ON \
  -DQUDA_MDW_FUSED_LS_LIST="8,12,16,20" \
  -DQUDA_DIRAC_STAGGERED=OFF \
  -DQUDA_DIRAC_TWISTED_MASS=OFF \
  -DQUDA_DIRAC_TWISTED_CLOVER=OFF \
  -DQUDA_DIRAC_WILSON=ON \
  -DQUDA_FORCE_GAUGE=OFF \
  -DQUDA_FORCE_HISQ=OFF \
  -DQUDA_GAUGE_ALG=OFF \
  -DQUDA_GAUGE_TOOLS=OFF \
  -DQUDA_QDPJIT=OFF \
  -DCUDAToolkit_ROOT=${CUDA_DIR} \
  -DQUDA_INTERFACE_QDPJIT=OFF \
  -DQUDA_INTERFACE_MILC=OFF \
  -DQUDA_INTERFACE_CPS=OFF \
  -DQUDA_INTERFACE_QDP=ON \
  -DQUDA_INTERFACE_TIFR=OFF \
  -DQUDA_QMP=ON \
  -DQMP_DIR=${INSTALLROOT}/qmp/lib/cmake/QMP \
  -DQUDA_QIO=OFF \
  -DQUDA_OPENMP=OFF \
  -DQUDA_MULTIGRID=ON \
  -DQUDA_NVSHMEM=OFF \
  -DQUDA_MAX_MULTI_BLAS_N=9 \
  -DQUDA_DOWNLOAD_EIGEN=ON \
  -DQUDA_EIGEN_VERSION=3.3.9 \
  -DQUDA_DOWNLOAD_USQCD=OFF \
  -DCMAKE_INSTALL_PREFIX=${INSTALLROOT}/quda \
  -DCMAKE_BUILD_TYPE="DEVEL" \
  -DCMAKE_CXX_COMPILER="mpicxx"\
  -DCMAKE_CXX_STANDARD=17 \
  -DCMAKE_CXX_EXTENSIONS=OFF \
  -DCMAKE_C_COMPILER="mpicc" \
  -DBUILD_SHARED_LIBS=ON \
  -DQUDA_BUILD_SHAREDLIB=ON \
  -DQUDA_BUILD_ALL_TESTS=OFF \
  -DQUDA_CTEST_DISABLE_BENCHMARKS=OFF \
  -DCMAKE_SHARED_LINKER_FLAGS="-L${CUDA_DIR}/lib64"

cmake --build . -j 32  -v
cmake --install .

popd
